version: '3'
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./flask_api/
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  frontend:
    build: ./react_frontend/
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata: {}
  

